# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tag: /tags
rss: /atom.xml

enable_links: true

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
